### ISSUE TITLE
Error encountered when using the compiled version of IPOPT with GAMS39

### ISSUE THREAD

**Issue by madabhushipb** [coin-or/GAMSlinks#2]
Hello,

I encountered the following error when I was using a locally compiled version of IPOPT with GAMS. I compiled GAMSlinks and followed the procedure outlined in the README.

![image](https://user-images.githubusercontent.com/62020250/186740055-1e238389-d79f-4468-b2bf-9eb7398a3039.png)

I configured the `GAMSlinks` build using the following command,

`./configure CC=gcc-11 CXX=g++-11 F77=gfortran-11 ADD_CXXFLAGS=-std=c++11 `

and the `IPOPT` build using the following command,

`./configure CC=gcc-11 CXX=g++-11 F77=gfortran-11`

**Comment by svigerske** [comment]
Is this macOS?

**Comment by madabhushipb** [comment]
Yes

**Comment by svigerske** [comment]
I remember getting this problem when `libstdc++` was loaded twice from different places.

It's a bit annoying, but try to change the libraries that you've build so that they use the libstdc++ that comes from GAMS, e.g.,
```
install_name_tool -change /path/to/system/libstdc++.dylib @rpath/libstdc++.dylib libipopt.dylib
```
Use `otool -L libipopt.dylib` to see what exactly `/path/to/system/libstdc++.dylib` should be.
You will need to do this also for `libGamsIpopt.dylib`.

**Comment by madabhushipb** [comment]
Great, thank you. That worked perfectly!
